// Frontend copy of the scannable stock universe, used only for watchlist
// autocomplete. The backend (api-server universe.ts) is the source of truth for
// scanning; this list just powers the add-ticker typeahead.

export interface UniverseEntry {
  ticker: string;
  name: string;
  sector: string;
}

export const STOCK_UNIVERSE: UniverseEntry[] = [
  // Technology
  { ticker: "AAPL",   name: "Apple",                      sector: "Technology" },
  { ticker: "MSFT",   name: "Microsoft",                  sector: "Technology" },
  { ticker: "NVDA",   name: "NVIDIA",                     sector: "Technology" },
  { ticker: "AMD",    name: "Advanced Micro Devices",     sector: "Technology" },
  { ticker: "AVGO",   name: "Broadcom",                   sector: "Technology" },
  { ticker: "CRM",    name: "Salesforce",                 sector: "Technology" },
  { ticker: "ADBE",   name: "Adobe",                      sector: "Technology" },
  { ticker: "ORCL",   name: "Oracle",                     sector: "Technology" },
  { ticker: "QCOM",   name: "Qualcomm",                   sector: "Technology" },
  { ticker: "CSCO",   name: "Cisco",                      sector: "Technology" },
  { ticker: "INTC",   name: "Intel",                      sector: "Technology" },
  { ticker: "TXN",    name: "Texas Instruments",          sector: "Technology" },
  { ticker: "AMAT",   name: "Applied Materials",          sector: "Technology" },
  { ticker: "LRCX",   name: "Lam Research",               sector: "Technology" },
  { ticker: "KLAC",   name: "KLA Corporation",            sector: "Technology" },
  { ticker: "ADI",    name: "Analog Devices",             sector: "Technology" },
  { ticker: "MU",     name: "Micron Technology",          sector: "Technology" },
  { ticker: "MRVL",   name: "Marvell Technology",         sector: "Technology" },
  { ticker: "SNPS",   name: "Synopsys",                   sector: "Technology" },
  { ticker: "CDNS",   name: "Cadence Design",             sector: "Technology" },
  { ticker: "PANW",   name: "Palo Alto Networks",         sector: "Technology" },
  { ticker: "CRWD",   name: "CrowdStrike",                sector: "Technology" },
  { ticker: "FTNT",   name: "Fortinet",                   sector: "Technology" },
  { ticker: "INTU",   name: "Intuit",                     sector: "Technology" },
  { ticker: "NOW",    name: "ServiceNow",                 sector: "Technology" },
  { ticker: "WDAY",   name: "Workday",                    sector: "Technology" },
  { ticker: "PLTR",   name: "Palantir",                   sector: "Technology" },
  { ticker: "DELL",   name: "Dell Technologies",          sector: "Technology" },
  { ticker: "HPQ",    name: "HP Inc.",                    sector: "Technology" },
  { ticker: "HPE",    name: "Hewlett Packard Enterprise", sector: "Technology" },
  { ticker: "IBM",    name: "IBM",                        sector: "Technology" },
  { ticker: "ACN",    name: "Accenture",                  sector: "Technology" },
  { ticker: "CTSH",   name: "Cognizant",                  sector: "Technology" },
  { ticker: "ADP",    name: "Automatic Data Processing",  sector: "Technology" },
  { ticker: "PAYX",   name: "Paychex",                    sector: "Technology" },
  { ticker: "FISERV", name: "Fiserv",                     sector: "Technology" },
  { ticker: "FIS",    name: "Fidelity National Info",     sector: "Technology" },
  { ticker: "GPN",    name: "Global Payments",            sector: "Technology" },
  { ticker: "KEYS",   name: "Keysight Technologies",      sector: "Technology" },
  { ticker: "CDW",    name: "CDW Corporation",            sector: "Technology" },
  { ticker: "MPWR",   name: "Monolithic Power",           sector: "Technology" },
  { ticker: "SWKS",   name: "Skyworks Solutions",         sector: "Technology" },
  { ticker: "NXPI",   name: "NXP Semiconductors",         sector: "Technology" },
  { ticker: "ON",     name: "ON Semiconductor",           sector: "Technology" },
  { ticker: "ANSS",   name: "ANSYS",                      sector: "Technology" },
  { ticker: "ROP",    name: "Roper Technologies",         sector: "Technology" },
  { ticker: "APP",    name: "AppLovin",                   sector: "Technology" },

  // Healthcare
  { ticker: "UNH",    name: "UnitedHealth Group",         sector: "Healthcare" },
  { ticker: "JNJ",    name: "Johnson & Johnson",          sector: "Healthcare" },
  { ticker: "LLY",    name: "Eli Lilly",                  sector: "Healthcare" },
  { ticker: "PFE",    name: "Pfizer",                     sector: "Healthcare" },
  { ticker: "MRK",    name: "Merck",                      sector: "Healthcare" },
  { ticker: "ABBV",   name: "AbbVie",                     sector: "Healthcare" },
  { ticker: "TMO",    name: "Thermo Fisher Scientific",   sector: "Healthcare" },
  { ticker: "ABT",    name: "Abbott Laboratories",        sector: "Healthcare" },
  { ticker: "DHR",    name: "Danaher",                    sector: "Healthcare" },
  { ticker: "BMY",    name: "Bristol-Myers Squibb",       sector: "Healthcare" },
  { ticker: "AMGN",   name: "Amgen",                      sector: "Healthcare" },
  { ticker: "GILD",   name: "Gilead Sciences",            sector: "Healthcare" },
  { ticker: "BSX",    name: "Boston Scientific",          sector: "Healthcare" },
  { ticker: "ISRG",   name: "Intuitive Surgical",         sector: "Healthcare" },
  { ticker: "ELV",    name: "Elevance Health",            sector: "Healthcare" },
  { ticker: "CVS",    name: "CVS Health",                 sector: "Healthcare" },
  { ticker: "CI",     name: "Cigna",                      sector: "Healthcare" },
  { ticker: "HUM",    name: "Humana",                     sector: "Healthcare" },
  { ticker: "REGN",   name: "Regeneron",                  sector: "Healthcare" },
  { ticker: "VRTX",   name: "Vertex Pharmaceuticals",     sector: "Healthcare" },
  { ticker: "BIIB",   name: "Biogen",                     sector: "Healthcare" },
  { ticker: "MRNA",   name: "Moderna",                    sector: "Healthcare" },
  { ticker: "ZBH",    name: "Zimmer Biomet",              sector: "Healthcare" },
  { ticker: "BAX",    name: "Baxter International",       sector: "Healthcare" },
  { ticker: "BDX",    name: "Becton Dickinson",           sector: "Healthcare" },
  { ticker: "IQV",    name: "IQVIA Holdings",             sector: "Healthcare" },
  { ticker: "IDXX",   name: "IDEXX Laboratories",         sector: "Healthcare" },
  { ticker: "SYK",    name: "Stryker",                    sector: "Healthcare" },
  { ticker: "MDT",    name: "Medtronic",                  sector: "Healthcare" },
  { ticker: "EW",     name: "Edwards Lifesciences",       sector: "Healthcare" },
  { ticker: "GEHC",   name: "GE HealthCare",              sector: "Healthcare" },
  { ticker: "HCA",    name: "HCA Healthcare",             sector: "Healthcare" },
  { ticker: "MOH",    name: "Molina Healthcare",          sector: "Healthcare" },
  { ticker: "CNC",    name: "Centene",                    sector: "Healthcare" },
  { ticker: "A",      name: "Agilent Technologies",       sector: "Healthcare" },

  // Financials
  { ticker: "JPM",    name: "JPMorgan Chase",             sector: "Financials" },
  { ticker: "BAC",    name: "Bank of America",            sector: "Financials" },
  { ticker: "WFC",    name: "Wells Fargo",                sector: "Financials" },
  { ticker: "GS",     name: "Goldman Sachs",              sector: "Financials" },
  { ticker: "MS",     name: "Morgan Stanley",             sector: "Financials" },
  { ticker: "C",      name: "Citigroup",                  sector: "Financials" },
  { ticker: "BLK",    name: "BlackRock",                  sector: "Financials" },
  { ticker: "SCHW",   name: "Charles Schwab",             sector: "Financials" },
  { ticker: "AXP",    name: "American Express",           sector: "Financials" },
  { ticker: "SPGI",   name: "S&P Global",                 sector: "Financials" },
  { ticker: "MCO",    name: "Moody's",                    sector: "Financials" },
  { ticker: "ICE",    name: "Intercontinental Exchange",  sector: "Financials" },
  { ticker: "CME",    name: "CME Group",                  sector: "Financials" },
  { ticker: "CBOE",   name: "Cboe Global Markets",        sector: "Financials" },
  { ticker: "BX",     name: "Blackstone",                 sector: "Financials" },
  { ticker: "KKR",    name: "KKR & Co.",                  sector: "Financials" },
  { ticker: "APO",    name: "Apollo Global Management",   sector: "Financials" },
  { ticker: "PGR",    name: "Progressive",                sector: "Financials" },
  { ticker: "TRV",    name: "Travelers Companies",        sector: "Financials" },
  { ticker: "ALL",    name: "Allstate",                   sector: "Financials" },
  { ticker: "MET",    name: "MetLife",                    sector: "Financials" },
  { ticker: "PRU",    name: "Prudential Financial",       sector: "Financials" },
  { ticker: "AIG",    name: "American International",     sector: "Financials" },
  { ticker: "AFL",    name: "Aflac",                      sector: "Financials" },
  { ticker: "USB",    name: "U.S. Bancorp",               sector: "Financials" },
  { ticker: "PNC",    name: "PNC Financial",              sector: "Financials" },
  { ticker: "TFC",    name: "Truist Financial",           sector: "Financials" },
  { ticker: "COF",    name: "Capital One",                sector: "Financials" },
  { ticker: "DFS",    name: "Discover Financial",         sector: "Financials" },
  { ticker: "SYF",    name: "Synchrony Financial",        sector: "Financials" },
  { ticker: "FITB",   name: "Fifth Third Bancorp",        sector: "Financials" },
  { ticker: "KEY",    name: "KeyCorp",                    sector: "Financials" },
  { ticker: "RF",     name: "Regions Financial",          sector: "Financials" },
  { ticker: "HBAN",   name: "Huntington Bancshares",      sector: "Financials" },
  { ticker: "MTB",    name: "M&T Bank",                   sector: "Financials" },

  // Consumer Discretionary
  { ticker: "AMZN",   name: "Amazon",                     sector: "Consumer Discretionary" },
  { ticker: "TSLA",   name: "Tesla",                      sector: "Consumer Discretionary" },
  { ticker: "HD",     name: "Home Depot",                 sector: "Consumer Discretionary" },
  { ticker: "LOW",    name: "Lowe's",                     sector: "Consumer Discretionary" },
  { ticker: "MCD",    name: "McDonald's",                 sector: "Consumer Discretionary" },
  { ticker: "SBUX",   name: "Starbucks",                  sector: "Consumer Discretionary" },
  { ticker: "NKE",    name: "Nike",                       sector: "Consumer Discretionary" },
  { ticker: "TGT",    name: "Target",                     sector: "Consumer Discretionary" },
  { ticker: "DIS",    name: "Walt Disney",                sector: "Consumer Discretionary" },
  { ticker: "BKNG",   name: "Booking Holdings",           sector: "Consumer Discretionary" },
  { ticker: "MAR",    name: "Marriott International",     sector: "Consumer Discretionary" },
  { ticker: "HLT",    name: "Hilton Worldwide",           sector: "Consumer Discretionary" },
  { ticker: "RCL",    name: "Royal Caribbean",            sector: "Consumer Discretionary" },
  { ticker: "CCL",    name: "Carnival",                   sector: "Consumer Discretionary" },
  { ticker: "ABNB",   name: "Airbnb",                     sector: "Consumer Discretionary" },
  { ticker: "F",      name: "Ford Motor",                 sector: "Consumer Discretionary" },
  { ticker: "GM",     name: "General Motors",             sector: "Consumer Discretionary" },
  { ticker: "TJX",    name: "TJX Companies",              sector: "Consumer Discretionary" },
  { ticker: "ROST",   name: "Ross Stores",                sector: "Consumer Discretionary" },
  { ticker: "ORLY",   name: "O'Reilly Automotive",        sector: "Consumer Discretionary" },
  { ticker: "AZO",    name: "AutoZone",                   sector: "Consumer Discretionary" },
  { ticker: "GPC",    name: "Genuine Parts",              sector: "Consumer Discretionary" },
  { ticker: "BBY",    name: "Best Buy",                   sector: "Consumer Discretionary" },
  { ticker: "EBAY",   name: "eBay",                       sector: "Consumer Discretionary" },
  { ticker: "ETSY",   name: "Etsy",                       sector: "Consumer Discretionary" },
  { ticker: "YUM",    name: "Yum Brands",                 sector: "Consumer Discretionary" },
  { ticker: "DRI",    name: "Darden Restaurants",         sector: "Consumer Discretionary" },
  { ticker: "LVS",    name: "Las Vegas Sands",            sector: "Consumer Discretionary" },
  { ticker: "MGM",    name: "MGM Resorts",                sector: "Consumer Discretionary" },
  { ticker: "WYNN",   name: "Wynn Resorts",               sector: "Consumer Discretionary" },

  // Consumer Staples
  { ticker: "WMT",    name: "Walmart",                    sector: "Consumer Staples" },
  { ticker: "COST",   name: "Costco",                     sector: "Consumer Staples" },
  { ticker: "PG",     name: "Procter & Gamble",           sector: "Consumer Staples" },
  { ticker: "KO",     name: "Coca-Cola",                  sector: "Consumer Staples" },
  { ticker: "PEP",    name: "PepsiCo",                    sector: "Consumer Staples" },
  { ticker: "PM",     name: "Philip Morris",              sector: "Consumer Staples" },
  { ticker: "MO",     name: "Altria Group",               sector: "Consumer Staples" },
  { ticker: "MDLZ",   name: "Mondelez International",     sector: "Consumer Staples" },
  { ticker: "GIS",    name: "General Mills",              sector: "Consumer Staples" },
  { ticker: "K",      name: "Kellanova",                  sector: "Consumer Staples" },
  { ticker: "HRL",    name: "Hormel Foods",               sector: "Consumer Staples" },
  { ticker: "CAG",    name: "ConAgra Brands",             sector: "Consumer Staples" },
  { ticker: "CPB",    name: "Campbell Soup",              sector: "Consumer Staples" },
  { ticker: "MKC",    name: "McCormick",                  sector: "Consumer Staples" },
  { ticker: "CL",     name: "Colgate-Palmolive",          sector: "Consumer Staples" },
  { ticker: "CHD",    name: "Church & Dwight",            sector: "Consumer Staples" },
  { ticker: "CLX",    name: "Clorox",                     sector: "Consumer Staples" },
  { ticker: "EL",     name: "Estee Lauder",               sector: "Consumer Staples" },
  { ticker: "KMB",    name: "Kimberly-Clark",             sector: "Consumer Staples" },
  { ticker: "STZ",    name: "Constellation Brands",       sector: "Consumer Staples" },
  { ticker: "TAP",    name: "Molson Coors",               sector: "Consumer Staples" },
  { ticker: "TSN",    name: "Tyson Foods",                sector: "Consumer Staples" },
  { ticker: "LW",     name: "Lamb Weston",                sector: "Consumer Staples" },
  { ticker: "KVUE",   name: "Kenvue",                     sector: "Consumer Staples" },
  { ticker: "SFM",    name: "Sprouts Farmers Market",     sector: "Consumer Staples" },

  // Communication Services
  { ticker: "GOOGL",  name: "Alphabet Class A",           sector: "Communication Services" },
  { ticker: "GOOG",   name: "Alphabet Class C",           sector: "Communication Services" },
  { ticker: "META",   name: "Meta Platforms",             sector: "Communication Services" },
  { ticker: "NFLX",   name: "Netflix",                    sector: "Communication Services" },
  { ticker: "CMCSA",  name: "Comcast",                    sector: "Communication Services" },
  { ticker: "T",      name: "AT&T",                       sector: "Communication Services" },
  { ticker: "VZ",     name: "Verizon",                    sector: "Communication Services" },
  { ticker: "TMUS",   name: "T-Mobile US",                sector: "Communication Services" },
  { ticker: "CHTR",   name: "Charter Communications",     sector: "Communication Services" },
  { ticker: "EA",     name: "Electronic Arts",            sector: "Communication Services" },
  { ticker: "TTWO",   name: "Take-Two Interactive",       sector: "Communication Services" },
  { ticker: "OMC",    name: "Omnicom Group",              sector: "Communication Services" },
  { ticker: "IPG",    name: "Interpublic Group",          sector: "Communication Services" },
  { ticker: "LYV",    name: "Live Nation",                sector: "Communication Services" },
  { ticker: "FOXA",   name: "Fox Corporation A",          sector: "Communication Services" },
  { ticker: "WBD",    name: "Warner Bros. Discovery",     sector: "Communication Services" },
  { ticker: "PARA",   name: "Paramount Global",           sector: "Communication Services" },
  { ticker: "NWSA",   name: "News Corp A",                sector: "Communication Services" },
  { ticker: "RBLX",   name: "Roblox",                     sector: "Communication Services" },
  { ticker: "SNAP",   name: "Snap",                       sector: "Communication Services" },
  { ticker: "PINS",   name: "Pinterest",                  sector: "Communication Services" },

  // Industrials
  { ticker: "GE",     name: "GE Aerospace",               sector: "Industrials" },
  { ticker: "HON",    name: "Honeywell",                  sector: "Industrials" },
  { ticker: "UPS",    name: "UPS",                        sector: "Industrials" },
  { ticker: "FDX",    name: "FedEx",                      sector: "Industrials" },
  { ticker: "BA",     name: "Boeing",                     sector: "Industrials" },
  { ticker: "LMT",    name: "Lockheed Martin",            sector: "Industrials" },
  { ticker: "RTX",    name: "RTX Corporation",            sector: "Industrials" },
  { ticker: "NOC",    name: "Northrop Grumman",           sector: "Industrials" },
  { ticker: "GD",     name: "General Dynamics",           sector: "Industrials" },
  { ticker: "CAT",    name: "Caterpillar",                sector: "Industrials" },
  { ticker: "DE",     name: "Deere & Company",            sector: "Industrials" },
  { ticker: "MMM",    name: "3M",                         sector: "Industrials" },
  { ticker: "EMR",    name: "Emerson Electric",           sector: "Industrials" },
  { ticker: "ETN",    name: "Eaton",                      sector: "Industrials" },
  { ticker: "PH",     name: "Parker Hannifin",            sector: "Industrials" },
  { ticker: "ITW",    name: "Illinois Tool Works",        sector: "Industrials" },
  { ticker: "DOV",    name: "Dover",                      sector: "Industrials" },
  { ticker: "ROK",    name: "Rockwell Automation",        sector: "Industrials" },
  { ticker: "AME",    name: "AMETEK",                     sector: "Industrials" },
  { ticker: "XYL",    name: "Xylem",                      sector: "Industrials" },
  { ticker: "GWW",    name: "W.W. Grainger",              sector: "Industrials" },
  { ticker: "MSI",    name: "Motorola Solutions",         sector: "Industrials" },
  { ticker: "WAB",    name: "Wabtec",                     sector: "Industrials" },
  { ticker: "UNP",    name: "Union Pacific",              sector: "Industrials" },
  { ticker: "CSX",    name: "CSX Corporation",            sector: "Industrials" },
  { ticker: "NSC",    name: "Norfolk Southern",           sector: "Industrials" },
  { ticker: "LDOS",   name: "Leidos Holdings",            sector: "Industrials" },
  { ticker: "SWK",    name: "Stanley Black & Decker",     sector: "Industrials" },

  // Energy
  { ticker: "XOM",    name: "Exxon Mobil",                sector: "Energy" },
  { ticker: "CVX",    name: "Chevron",                    sector: "Energy" },
  { ticker: "COP",    name: "ConocoPhillips",             sector: "Energy" },
  { ticker: "SLB",    name: "SLB",                        sector: "Energy" },
  { ticker: "EOG",    name: "EOG Resources",              sector: "Energy" },
  { ticker: "MPC",    name: "Marathon Petroleum",         sector: "Energy" },
  { ticker: "PSX",    name: "Phillips 66",                sector: "Energy" },
  { ticker: "OXY",    name: "Occidental Petroleum",       sector: "Energy" },
  { ticker: "VLO",    name: "Valero Energy",              sector: "Energy" },
  { ticker: "WMB",    name: "Williams Companies",         sector: "Energy" },
  { ticker: "KMI",    name: "Kinder Morgan",              sector: "Energy" },
  { ticker: "LNG",    name: "Cheniere Energy",            sector: "Energy" },
  { ticker: "DVN",    name: "Devon Energy",               sector: "Energy" },
  { ticker: "FANG",   name: "Diamondback Energy",         sector: "Energy" },
  { ticker: "HAL",    name: "Halliburton",                sector: "Energy" },
  { ticker: "BKR",    name: "Baker Hughes",               sector: "Energy" },
  { ticker: "APA",    name: "APA Corporation",            sector: "Energy" },
  { ticker: "MRO",    name: "Marathon Oil",               sector: "Energy" },
  { ticker: "EQT",    name: "EQT Corporation",            sector: "Energy" },
  { ticker: "TRGP",   name: "Targa Resources",            sector: "Energy" },

  // Real Estate
  { ticker: "AMT",    name: "American Tower",             sector: "Real Estate" },
  { ticker: "PLD",    name: "Prologis",                   sector: "Real Estate" },
  { ticker: "CCI",    name: "Crown Castle",               sector: "Real Estate" },
  { ticker: "EQIX",   name: "Equinix",                    sector: "Real Estate" },
  { ticker: "PSA",    name: "Public Storage",             sector: "Real Estate" },
  { ticker: "O",      name: "Realty Income",              sector: "Real Estate" },
  { ticker: "SPG",    name: "Simon Property Group",       sector: "Real Estate" },
  { ticker: "WELL",   name: "Welltower",                  sector: "Real Estate" },
  { ticker: "VICI",   name: "VICI Properties",            sector: "Real Estate" },
  { ticker: "EXR",    name: "Extra Space Storage",        sector: "Real Estate" },
  { ticker: "AVB",    name: "AvalonBay Communities",      sector: "Real Estate" },
  { ticker: "EQR",    name: "Equity Residential",         sector: "Real Estate" },
  { ticker: "DLR",    name: "Digital Realty Trust",       sector: "Real Estate" },
  { ticker: "ARE",    name: "Alexandria Real Estate",     sector: "Real Estate" },
  { ticker: "BXP",    name: "BXP Inc.",                   sector: "Real Estate" },
  { ticker: "IRM",    name: "Iron Mountain",              sector: "Real Estate" },

  // Utilities
  { ticker: "NEE",    name: "NextEra Energy",             sector: "Utilities" },
  { ticker: "DUK",    name: "Duke Energy",                sector: "Utilities" },
  { ticker: "SO",     name: "Southern Company",           sector: "Utilities" },
  { ticker: "D",      name: "Dominion Energy",            sector: "Utilities" },
  { ticker: "AEP",    name: "American Electric Power",    sector: "Utilities" },
  { ticker: "EXC",    name: "Exelon",                     sector: "Utilities" },
  { ticker: "SRE",    name: "Sempra",                     sector: "Utilities" },
  { ticker: "XEL",    name: "Xcel Energy",                sector: "Utilities" },
  { ticker: "PEG",    name: "PSEG",                       sector: "Utilities" },
  { ticker: "ED",     name: "Consolidated Edison",        sector: "Utilities" },
  { ticker: "EIX",    name: "Edison International",       sector: "Utilities" },
  { ticker: "AWK",    name: "American Water Works",       sector: "Utilities" },
  { ticker: "WEC",    name: "WEC Energy Group",           sector: "Utilities" },
  { ticker: "ES",     name: "Eversource Energy",          sector: "Utilities" },

  // Materials
  { ticker: "LIN",    name: "Linde",                      sector: "Materials" },
  { ticker: "APD",    name: "Air Products",               sector: "Materials" },
  { ticker: "ECL",    name: "Ecolab",                     sector: "Materials" },
  { ticker: "SHW",    name: "Sherwin-Williams",           sector: "Materials" },
  { ticker: "FCX",    name: "Freeport-McMoRan",           sector: "Materials" },
  { ticker: "NEM",    name: "Newmont",                    sector: "Materials" },
  { ticker: "NUE",    name: "Nucor",                      sector: "Materials" },
  { ticker: "CF",     name: "CF Industries",              sector: "Materials" },
  { ticker: "MOS",    name: "Mosaic",                     sector: "Materials" },
  { ticker: "ALB",    name: "Albemarle",                  sector: "Materials" },
  { ticker: "PPG",    name: "PPG Industries",             sector: "Materials" },
  { ticker: "VMC",    name: "Vulcan Materials",           sector: "Materials" },
  { ticker: "MLM",    name: "Martin Marietta",            sector: "Materials" },
  { ticker: "STLD",   name: "Steel Dynamics",             sector: "Materials" },
  { ticker: "RPM",    name: "RPM International",          sector: "Materials" },
];
