// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/crypto-predictor/Bloomberg.tsx": () => import("../components/mockups/crypto-predictor/Bloomberg.tsx"),
  "./components/mockups/crypto-predictor/CardDeck.tsx": () => import("../components/mockups/crypto-predictor/CardDeck.tsx"),
  "./components/mockups/crypto-predictor/Glassmorphism.tsx": () => import("../components/mockups/crypto-predictor/Glassmorphism.tsx"),
  "./components/mockups/crypto-predictor/Synthwave.tsx": () => import("../components/mockups/crypto-predictor/Synthwave.tsx"),
  "./components/mockups/crypto-predictor/Terminal.tsx": () => import("../components/mockups/crypto-predictor/Terminal.tsx")
};
